// Generated by https://quicktype.io
import type { AxiosError } from 'axios'

export interface ProductStoreType {
  error: null | AxiosError
  getProducts: (search: string, data: { order: string } | null) => void
  products: Element[]
  loading: boolean
}

export interface ProductsTypes {
  elements?: Element[]
}

export interface Element {
  name: null | string
  description: null | string
  calculatedPrice: CalculatedPrice
}

export interface CalculatedPrice {
  unitPrice: number
}
